name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build debug
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Build Debug Linux
      run: cargo +nightly build --target aarch64-unknown-linux-musl --verbose
    
  test:
    name: Run tests
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo +nightly test --verbose
