name: Nightly

on:
  push:
    branches: [ "nightly" ]
  pull_request:
    branches: [ "nightly" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aarch64-unknown-linux-musl:
    name: Build ARM64 Linux
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Build ARM64 Linux
      run: cargo +nightly build --target aarch64-unknown-linux-musl --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/aarch64-unknown-linux-musl/release/client aarch64-linux-client
        cp ./target/aarch64-unknown-linux-musl/release/server aarch64-linux-server
    - uses: actions/upload-artifact@v3
      with:
        path: |
          aarch64-linux-client
          aarch64-linux-server

  x86_64-unknown-linux-musl:
    name: Build X86_64 Linux
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Build X86_64 Linux
      run: cargo +nightly build -Z build-std=std,panic_abort --target x86_64-unknown-linux-musl --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/x86_64-unknown-linux-musl/release/client x86_64-linux-client
        cp ./target/x86_64-unknown-linux-musl/release/server x86_64-linux-server
    - uses: actions/upload-artifact@v3
      with:
        path: |
          x86_64-linux-client
          x86_64-linux-server

  aarch64-pc-windows-msvc:
    name: Build ARM64 Windows
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Build ARM64 Windows
      run: cargo +nightly build -Z build-std=panic_abort --target aarch64-pc-windows-msvc --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/aarch64-pc-windows-msvc/release/client.exe aarch64-windows-client.exe
        cp ./target/aarch64-pc-windows-msvc/release/server.exe aarch64-windows-server.exe
    - uses: actions/upload-artifact@v3
      with:
        path: |
          aarch64-windows-client.exe
          aarch64-windows-server.exe

  x86_64-pc-windows-msvc:
    name: Build X86_64 Windows
    runs-on: server

    steps:
    - name: Build X86_64 Windows
      run: cargo +nightly build -Z build-std=panic_abort --target x86_64-pc-windows-msvc --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/x86_64-pc-windows-msvc/release/client.exe x86_64-windows-client.exe
        cp ./target/x86_64-pc-windows-msvc/release/server.exe x86_64-windows-server.exe
    - uses: actions/upload-artifact@v3
      with:
        path: |
          x86_64-windows-client.exe
          x86_64-windows-server.exe

  aarch64-apple-darwin:
    name: Build ARM64 MacOS
    runs-on: server

    steps:
    - name: Build ARM64 MacOS
      run: CC=aarch64-apple-darwin20.2-cc CXX=aarch64-apple-darwin20.2-c++ cargo +nightly build -Z build-std=std,panic_abort --target aarch64-apple-darwin --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/aarch64-apple-darwin/release/client aarch64-apple-client
        cp ./target/aarch64-apple-darwin/release/server aarch64-apple-server
    - uses: actions/upload-artifact@v3
      with:
        path: |
          aarch64-apple-client
          aarch64-apple-server

  x86_64-apple-darwin:
    name: Build X86_64 MacOS
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Build x86_64 MacOS
      run: CC=aarch64-apple-darwin20.2-cc CXX=aarch64-apple-darwin20.2-c++ cargo +nightly build -Z build-std=std,panic_abort --target x86_64-apple-darwin --release --verbose
    - name: Copy nightly binary
      run: |
        cp ./target/x86_64-apple-darwin/release/client x86_64-apple-client
        cp ./target/x86_64-apple-darwin/release/server x86_64-apple-server
    - uses: actions/upload-artifact@v3
      with:
        path: |
          x86_64-apple-client
          x86_64-apple-server

  test:
    name: Run tests
    runs-on: server

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo +nightly test --verbose